# Generated by Django 5.1.6 on 2025-03-05 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GasCylinderSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('cylinder_size', models.CharField(max_length=50)),
                ('quantity_sold', models.PositiveIntegerField()),
                ('price_per_cylinder', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas_shop.attendant')),
            ],
        ),
    ]
